server:
  port: 9001
spring:
  webflux:
    base-path: /api/order/v1
  r2dbc:
    url: r2dbc:mysql://localhost:3306/mysql #jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: root
    password: root
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: httptrace,loggers,health,info,metrics
  endpoint:
    loggers:
      enabled: true

springdoc:
  api-docs:
    enabled: true